services:
  app:
    build:
      context: .
    image: nextjs-dev
    ports:
      - "3000:3000"
      # for hot reload pang synchonize ng file system inside Container
      # if ever may changes ay realtime na magpapkita yung changes sa UI
      # ilalagay mo lang yan after ng docker compose up.
      # kaya gawin mo copy mo muna hanggang ports: 3000:3000
    environment:
      NODE_ENV: development
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
          ignore:
            - node_modules
        - action: rebuild
          path: package.json
